# Generated by Django 3.2.18 on 2023-03-20 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='instructions',
            field=models.TextField(default=''),
        ),
    ]
